
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf1:\x9d\xb9\x075\x80\xbe\xb7&EZ:}R<'
    
_lr_action_items = {'WORD':([0,],[1,]),'NUMBER':([3,],[6,]),'VALUE':([3,],[5,]),'EQUALS':([1,],[3,]),'NOTHING':([3,],[4,]),'$end':([2,4,5,6,],[0,-3,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> WORD EQUALS VALUE','sentence',3,'p_sentence','/home/jaineshdoshi/Documents/GPGPU-sim/gpgpu-sim/v3.x/aerialvision/lexyaccbookmark.py',120),
  ('sentence -> WORD EQUALS NUMBER','sentence',3,'p_sentence','/home/jaineshdoshi/Documents/GPGPU-sim/gpgpu-sim/v3.x/aerialvision/lexyaccbookmark.py',121),
  ('sentence -> WORD EQUALS NOTHING','sentence',3,'p_sentence','/home/jaineshdoshi/Documents/GPGPU-sim/gpgpu-sim/v3.x/aerialvision/lexyaccbookmark.py',122),
]
